show_message:
  target:
    entity:
      integration: musicpal
      domain: media_player
  fields:
    message:
      required: true
      example: "Dinner is ready"
      selector:
        text:

show_clock:
  target:
    entity:
      integration: musicpal
      domain: media_player

reboot:
  target:
    entity:
      integration: musicpal
      domain: media_player
